Report error and abort when given invalid command line options

diff --git a/npmi b/npmi
--- a/npmi
+++ b/npmi
@@ -72,6 +72,9 @@ parse_args() {
             t)
                 REDIS_TTL="$OPTARG"
                 ;;
+            *)
+                echo "ERROR: Invalid command line option(s) given"
+                exit 1
         esac
     done
 }
